
import javax.swing.JOptionPane;
//import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
//import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.SwingUtilities;
//import javax.swing.UIManager;
//import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yulianti
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupDari = new javax.swing.ButtonGroup();
        btnGrupKe = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbCelcius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbCalvin = new javax.swing.JRadioButton();
        rbCelcius2 = new javax.swing.JRadioButton();
        rbFahrenheit2 = new javax.swing.JRadioButton();
        rbCalvin2 = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERSI SUHU");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);

        jLabel1.setText("Input");

        jLabel2.setText("Dari");

        jLabel3.setText("Ke");

        btnGrupDari.add(rbCelcius);
        rbCelcius.setText("Celcius");

        btnGrupDari.add(rbFahrenheit);
        rbFahrenheit.setText("Fahrenheit");

        btnGrupDari.add(rbCalvin);
        rbCalvin.setText("Calvin");

        btnGrupKe.add(rbCelcius2);
        rbCelcius2.setText("Celcius");
        rbCelcius2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelcius2ActionPerformed(evt);
            }
        });

        btnGrupKe.add(rbFahrenheit2);
        rbFahrenheit2.setText("Fahrenheit");

        btnGrupKe.add(rbCalvin2);
        rbCalvin2.setText("Calvin");

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        jLabel4.setText("Hasil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfHasil))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFahrenheit)
                                    .addComponent(rbCelcius)
                                    .addComponent(rbCalvin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCalvin2)
                                    .addComponent(rbCelcius2)
                                    .addComponent(rbFahrenheit2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCelcius)
                    .addComponent(rbCelcius2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFahrenheit)
                    .addComponent(rbFahrenheit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCalvin)
                    .addComponent(rbCalvin2))
                .addGap(18, 18, 18)
                .addComponent(btnKonversi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCelcius2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelcius2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCelcius2ActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        //float suhu ;
        float celcius ;
        float calvin ;
        float fahrenheit ;
        float hasil = 0 ;               
        
        //kalo kosong pengen muncul error message tapi gajalan pemirsaaaaa
        if(tfInput.getText().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Input Tidak Boleh Kosong", "error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        //nyampe sini
        float suhu = Float.parseFloat(tfInput.getText());
        //asem salah posisi doang. jika di konversi ke float baru di cek gak bakal jalan
        
        if (rbCelcius.isSelected() && rbCalvin2.isSelected()) 
            hasil = suhu + 273;
        else if (rbCelcius.isSelected() && rbFahrenheit2.isSelected())
            hasil = (float) (1.8 * (suhu + 32));
        else if (rbFahrenheit.isSelected() && rbCelcius2.isSelected())
            hasil = (float) (0.55 * (suhu - 32));
        else if (rbFahrenheit.isSelected() && rbCalvin2.isSelected() )
            hasil = (float) (0.55 * (suhu - 32) + 273);
        else if (rbCalvin.isSelected() && rbCelcius2.isSelected())
            hasil = suhu - 273;
        else if (rbCalvin.isSelected() && rbFahrenheit2.isSelected())
            hasil = (float) (1.8 *(suhu-273)+32);
        
        else if (rbCelcius.isSelected() && rbCelcius2.isSelected())
            JOptionPane.showMessageDialog(null, "Pilih ke Fahrenheit atau Calvin", "ERROR", JOptionPane.ERROR_MESSAGE);
        else if (rbFahrenheit.isSelected() && rbFahrenheit2.isSelected())
            JOptionPane.showMessageDialog(null, "Pilih ke Celcius atau Calvin", "ERROR", JOptionPane.ERROR_MESSAGE);
        else if (rbCalvin.isSelected() && rbCalvin2.isSelected())
            JOptionPane.showMessageDialog(null, "Pilih ke Fahrenheit atau Celcius", "ERROR", JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Pilih Salah Satu Type Suhu", "ERROR", JOptionPane.ERROR_MESSAGE);
        
        tfHasil.setText(String.valueOf(hasil));
        return;
        //kalo abis convert balikin inputan gimana ya :v ?
        
    }//GEN-LAST:event_btnKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupDari;
    private javax.swing.ButtonGroup btnGrupKe;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbCalvin;
    private javax.swing.JRadioButton rbCalvin2;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbCelcius2;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbFahrenheit2;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfInput;
    // End of variables declaration//GEN-END:variables
}
